### ISSUE TITLE
Docker container crashes when processing an image 

### ISSUE THREAD

**Issue by paul9115** [mallorbc/stable-diffusion-klms-gui#11]
I have tried this with both text to image and image to image with the same result. With the dockerfile from #5 we get the following output from the crash 
![image](https://user-images.githubusercontent.com/32612194/189981223-9fc761df-5823-4dc8-947f-08453b3b8917.png)

Using the main branch for builiding and running the image and copied over the ckpt file from Huggingface into /diffusion_model/model.ckpt 

Using an Arch system with an nvidia RTX-3060ti gpu the nvidia-docker package from the AUR (20.10.18) and latest nvidia drivers/kernel installed 
![image](https://user-images.githubusercontent.com/32612194/189983234-d1c05657-dd9f-4be2-9261-f7a9e5b9ebc4.png)

**Comment by mallorbc** [comment]
How much RAM do you have?

**Comment by paul9115** [comment]
32GB. The crash seems to happen almost immediately when attempting to process the image if that helps at all. Or if there's any way of collecting more debug information I would be more than happy to do so!

**Comment by paul9115** [comment]
If it helps, I created a video showing the image and resource usage as the crash happens

https://user-images.githubusercontent.com/32612194/194765203-5987837a-27b1-4451-bc2a-7bfc6152bd47.mp4

**Comment by paul9115** [comment]
Ok, so I have tracked down the issue to a failing power supply. I guess the GPU wasn't getting enough power
