### ISSUE TITLE
Any way to cache the downloads that happen during startup?

### ISSUE THREAD

**Issue by darkvertex** [mallorbc/stable-diffusion-klms-gui#12]
I noticed each time I start the image it downloads a few things... Any way I can cache them with another mount?

**Comment by paul9115** [comment]
There is an included script in the docker directory `save_container.sh`  run that once the container is finished building and is running

**Comment by darkvertex** [comment]
`docker commit` (from `save_container.sh`) does the job but I prefer to go with more mounts so they're easy to wipe if I need to, without having to rebuild the image again.

So basically, I `cd`'d into the repo clone and created two new dirs (`mkdir .cache gfpgan`) then took the command from https://github.com/mallorbc/stable-diffusion-klms-gui/blob/main/run_image.sh
and added two more volume mounts in the flags:

```
-v `pwd`/gfpgan:/app/gfpgan -v `pwd`/.cache:/root/.cache
```

There's some PyTorch stuff that gets put in /root/.cache and /gfpgan gets the upscaling model autodownloaded to it.

After that it downloaded stuff once then subsequent runs were snappy and didn't download more stuff.
