### ISSUE TITLE
Javascript error when selecting Mask Image editor mode

### ISSUE THREAD

**Issue by isieo** [mallorbc/stable-diffusion-klms-gui#3]
I am getting a js error when i select "Mask" image editor mode. After this error, all ui interaction will not work until i page refresh 

![image](https://user-images.githubusercontent.com/172893/188873608-6b1e45ae-83b4-495c-afa2-0734f5941598.png)
![image](https://user-images.githubusercontent.com/172893/188873642-187f61b6-3fcf-4852-a7e9-4d50ae6cfca8.png)

**Comment by arielgk** [comment]
Seems it's is a known Gradio bug
https://github.com/gradio-app/gradio/issues/2194
I've updated gradio to 3.2.1b2 and got rid of the error

**Comment by mallorbc** [comment]
merged PR
