### ISSUE TITLE
error after running run_image.sh

### ISSUE THREAD

**Issue by jimqartworks** [mallorbc/stable-diffusion-klms-gui#6]
I'm using Ubuntu inside my Mac. 

<img width="965" alt="Screen Shot 2022-09-07 at 1 15 28 PM" src="https://user-images.githubusercontent.com/112999421/188969503-93066127-0893-4ef1-88dd-fdca4192c7e7.png">
<img width="880" alt="Screen Shot 2022-09-07 at 1 20 21 PM" src="https://user-images.githubusercontent.com/112999421/188969746-54e19974-5b21-4431-b97a-24cc0e346e53.png">

**Comment by TheMotonaut** [comment]
Seems like you dont fulfill the requirements for this library. You need a GPU

**Comment by mallorbc** [comment]
Its possible to have a GPU passthrough with a VM, but it is not always the easiest.  You need a Nvidia GPU for this repo
