### ISSUE TITLE
Run_image.sh exited without any message

### ISSUE THREAD

**Issue by hilmiyafia** [mallorbc/stable-diffusion-klms-gui#9]
![Error](https://user-images.githubusercontent.com/56539775/189183383-9cb7d918-fcc4-427d-be04-1abc92242500.png)

Please help, I tried running run_image.sh but it exited after downloading the second file.

**Comment by FoxBlocks** [comment]
Exact same problem here. I'm on Windows 11 using WSL2. I have a 3050 Ti Laptop.

**Comment by Batman313v** [comment]
It looks like you're using docker inside a linux install on windows. I would recommend trying with docker desktop and enabling the wsl 2 integration. A common issue appears to be not enough ram. This model requires at least 32gb of ram available to the container. You could also try using the docker-compose file I put in issue #5 and see if that helps or at least gets you an error code to go off of.

**Comment by Batman313v** [comment]
You could try using the docker-compose file I put in issue https://github.com/mallorbc/stable-diffusion-klms-gui/issues/5 and see if that helps or at least gets you an error code to go off of.

**Comment by Batman313v** [comment]
> Exact same problem here. I'm on Windows 11 using WSL2. I have a 3050 Ti Laptop.

Check out my reply on #5 and see if that helps as that thread is specific to WSL and windows where it looks like OP is using a debian distro

**Comment by FoxBlocks** [comment]
Ah, that's why. I have 16GB of RAM. Shouldn't the requirements have the minimum RAM in them so others don't run into this problem?

**Comment by Batman313v** [comment]
> Ah, that's why. I have 16GB of RAM. Shouldn't the requirements have the minimum RAM in them so others don't run into this problem?

Yea, the model is still pretty new so I don't know if the devs have really pushed the limits yet.

**Comment by FoxBlocks** [comment]
Okay. Thank you for your help!

**Comment by hilmiyafia** [comment]
@Batman313v Thank you for the suggestion. It seems I have the same memory problem. I only have 16 gb ram. Is there no other way?

**Comment by Batman313v** [comment]
> @Batman313v Thank you for the suggestion. It seems I have the same memory problem. I only have 16 gb ram. Is there no other way?

I'm still looking into potential ways of making this work but so far it looks like 32 gbs is the minimum. This is at least the case for Windows WSl. Windows combined with docker uses almost 7gb of ram on their own before spinning up and containers. I'll keep looking into it today and post back here with any updates.

**Comment by hilmiyafia** [comment]
@Batman313v Thank you 😊

**Comment by Batman313v** [comment]
Update: It is possible to run on 16gb of RAM. It looks like building the container, saving it after downloads finish, and then spinning up the saved container allows it to run with 16gb and default settings. The setup is using an RTX 3060 TI running Windows 10, WSL 2.0, docker desktop, and Nvidia Cuda tools 10.2.89 with 16Gb of DDr4 ram at 3200 MHz, and an Intel i5-10600K at 4.5 GHz. This setup consumes an average of 12.8gbs RAM and is ~80% stable.

Things to note: It WILL crash if you are running ANY other containers at the same time. If you change any settings other than the Batch Count, Seed, Sample steps, and options in the Advanced tab then it will crash. You can lower the output resolution but cannot go any higher than 512x512. Changing the Sampling method is unpredictable and not recommended as it can (but doesn't always) cause a crash. To be clear; "Stable" does NOT mean indestructible or easy to work with. 

The only way I could get this to run was setting my systems Virtual Memory at 30GB. I do not have a way to confirm this but I believe doing this is allowing the system to move other programs and possible some windows data stored in RAM temporarily to the M.2 drive while the system installs. 

![16gb](https://user-images.githubusercontent.com/25057949/189467653-80993000-098e-444a-8949-bf0a0134de35.png)
@hilmiyafia

**Comment by Batman313v** [comment]
@hilmiyafia and anyone else looking at trying to run with 16GB Ram.

Check out the [sd-webui](https://github.com/sd-webui/stable-diffusion-webui). It seems to be better optimized using around 10GB and installed without any modification. The repo is pretty new as it was migrated from a previous version so the documentation isn't all the way there yet. Here is the info for a [Docker installation](https://github.com/sd-webui/stable-diffusion-webui/discussions/922)

**Comment by hilmiyafia** [comment]
@Batman313v It works! 😁 sd-webui only use 3 GB of my memory. I don't use the docker or linux. I run it directly on my windows python 3.7. Thank you so much! 😊😊

**Comment by mallorbc** [comment]
If you have Linux you can run this with 16GB or less RAM.  24 or 32GB of RAM is need for Windows
